### ISSUE TITLE
dune runtest gives an error in ssl_error test

### ISSUE THREAD

**Issue by craff** [savonet/ocaml-ssl#137]
```
File "tests/dune", line 13, characters 7-15:
13 |  (name ssl_comm)
            ^^^^^^^^
Testing `Ssl communication'.
This run has ID `WYHZXY0C'.

  [OK]          Communication          0   Test init.
> [FAIL]        Communication          1   Test error queue.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        Communication          1   Test error queue.                   │
└──────────────────────────────────────────────────────────────────────────────┘
ASSERT Error code
File "tests/ssl_comm.ml", line 12, character 4:
FAIL Error code

   Expected: `268959746'
   Received: `537346050'
```

**Comment by craff** [comment]
Independent, but doesn't it need a deps as in:
```
(test
 (name ssl_comm)
 (modules ssl_comm)
 (libraries ssl alcotest)
 (deps expired.pem))
```

**Comment by anmonteiro** [comment]
works for me. which version of open ssl?

**Comment by craff** [comment]
debian package : 1.1.1n-0+deb11u4
I am now upgrading to 1.1.1n-0+deb11u5

**Comment by anmonteiro** [comment]
@Firgeis could this failing test be >= openssl 3.0?

**Comment by craff** [comment]
May be ? You have openssl > 3.0 I guess. So it should be that.

**Comment by craff** [comment]
Where does the error code comes from ?

**Comment by Firgeis** [comment]
I think this might be actually openssl < 3

**Comment by Firgeis** [comment]
Maybe it would be useful to export a function to ascertain the version

**Comment by Firgeis** [comment]
I could not reproduce, tried: 3.0.8 3.0.5 1.1.1f (ubuntu) and 1.1.1n (debian)

**Comment by craff** [comment]
> I could not reproduce, tried: 3.0.8 3.0.5 1.1.1f (ubuntu) and 1.1.1n (debian)

I have the same debian version as you I guess... I would investigate in more detail.

**Comment by craff** [comment]
The first code ssl_com expect is 
268959746 = 0x10080002 which gives
lib            0x10 = 16 =  ERR_LIB_EC (from my openssl/err.h in openssl 1.1.1n)

the code I get is
537346050 = 0x20074002
lib = 0x20 = 32 = ERR_LIB_BIO (from err. h too)

And the expected string is BIO_routines.

Are you sure the code expected by ssl_comm.ml is correct ?

**Comment by craff** [comment]
#139 should solve this issue and be more stable for futur version of openssl.
