### ISSUE TITLE
Downstream build broken after openssl 3.3.1 upgrade

### ISSUE THREAD

**Issue by jonsterling** [savonet/ocaml-ssl#154]
After running `brew upgrade`, my MacBook's openssl installation got upgraded from 3.3.0 to 3.3.1. Suddenly, I am unable to build OCaml packages that depend on `ssl`; Homebrew doesn't seem to let me downgrade the system library, so I am really completely stuck. 

This doesn't appear to be the first time something like this has happened (https://github.com/savonet/ocaml-ssl/issues/153) — but, I can't really figure out whose fault it is (it may be caused by homebrew or something?). As this is a recurring problem, can we find a permanent solution?

**Comment by anmonteiro** [comment]
Could you provide more information about your issue? So far this and #153 seem like homebrew problems which should rather be reported in their issue tracker.

**Comment by jonsterling** [comment]
@anmonteiro Thanks! And sorry if this is not caused by `ssl`. The issue I have is a linker error. For example, one month ago, homebrew upgraded my system `openssl` installation from `3.2.1` to `3.3.0`. After this upgrade, any OCaml builds that depended on the `ssl` library would fail with an error like the following:

```
	ld: warning: search path '/opt/homebrew/Cellar/openssl@3/3.2.1/lib' not 
found
	ld: warning: search path '/opt/Homebrew/Cellar/openssl@3/3.1.2/lib' not 
found
	ld: library 'ssl' not found
	clang: error: linker command failed with exit code 1 (use -v to see 
invocation)
	File "caml_startup", line 1:
	Error: Error during linking (exit code 1)
```

Interestingly, after running `opam upgrade`, this problem resolved itself — but I cannot figure out what exactly happened to fix it. _This is the reason that I think, even if this is the Homebrew packagers' fault ultimately, there is definitely some kind of `opam` involvement_ — which led me to post on this package's ticket tracker.

Note that this happened again yesterday, when homebrew upgraded my openssl from `3.3.0` to `3.3.1`. Unfortunately, running `opam upgrade` did not solve the problem like it did last time (and I guess I have no reason to believe it would have solved it, given that I still do not understand the mechanism by which the problem resolved itself last time).

Sorry for all the vagueness here — it's inherently very hard to nail down what is happening because we are dealing with a problem that involves a combination of edge cases in several tools and libraries, on a platform that (apparently) very few OCaml programmers use.

**Comment by jonsterling** [comment]
If you do think that there is no way for this to be related to the `ssl` package, please feel free to close this ticket and accept my apologies for the noise.

**Comment by anmonteiro** [comment]
@jonsterling if you still have a broken system, this is easy to debug:

- clone this repo
- run `dune build`
- check `_build/default/src/c_library_flags.sexp` to see if they have the expected paths


post the results here

**Comment by jonsterling** [comment]
Thanks very much for the suggestion! I will see if I can do this.

**Comment by jonsterling** [comment]
Unfortunately, I can no longer reproduce this issue. Closing ticket, as I don't think there is anything that can be done at this time (and it's likely homebrew's fault).
