### ISSUE TITLE
Tagged versions including the configure script?

### ISSUE THREAD

**Issue by djs55** [savonet/ocaml-ssl#21]
Hi,

To workaround the recent sourceforge outtage I changed the opam-repository to point to the github mirror, specifically the magic link which allows a tagged version to be downloaded as a .tar.gz. Unfortunately these tarballs don't contain the configure script so I added it directly to the opam-repository: have a look at [ocaml/opam-repository#4477]. This works but is obviously a bit ugly :)

It would be really nice if there could exist tarballs generated by github which contain the configure scripts i.e. if they were more similar to the official release tarballs. Assuming you want to keep the current meaning of the existing tags, perhaps this could be achieved by adding a parallel set of tags (e.g. release-x.y.z) which had the autogen stuff added? What do you think?

Thanks for writing these bindings btw! :)

**Comment by toots** [comment]
Hi,

We're gonna do a full release of all modules & liquidsoap on github soon.

**Comment by smimram** [comment]
Yes, I just uploaded the tar.gz on the ocaml-ssl release page. I guess this is enough? (feel free to reopen otherwise)

**Comment by toots** [comment]
Wanna try to update the `opam` package @smimram ? :-)
