### ISSUE TITLE
Broken on OS X now, simple fix methinks

### ISSUE THREAD

**Issue by fxfactorial** [savonet/ocaml-ssl#22]
I think the new El Captain update changed the way `/usr/local` is done and it broke some bindings. 

The current configure script errors would with 
```
checking for openssl/ssl.h... no
configure: error: Cannot find libssl headers.
```
(Yes I have the headers installed) In my bindings the fix is to explicitly do something like `-I/usr/local/include` and `-L/usr/local/lib` for the compiler flags, not sure what the equivalent is for auto tools stack.

**Comment by smimram** [comment]
I am using only very standard macros here, so I would be very surprised to be the only one broken here. Moreover, I don't know anything about OS X specificities, so I am afraid I cannot help much (but I am of course willing to integrate any decent patch).

**Comment by fxfactorial** [comment]
I would provide a patch but I don't know anything about the autotools stack. All I know is that ocaml-ssl is currently not compiling/installing correctly on OS X and that I suspect the fix is easy, tell the configure script to also look in `/usr/local/include`

**Comment by haoyang** [comment]
`./configure CFLAGS='-I/usr/local/include'` works for me.

**Comment by sylvarant** [comment]
I have the same issue on El Capitan, with openssl installed through homebrew.
`./configure CFLAGS=-I/usr/local/opt/openssl/include`
works for me

**Comment by fxfactorial** [comment]
I've said this before, the fix is trivial, just asking if @smimram can add this to the build configuration for OS X or maybe get this added to the opam file on opam if @smimram is unwilling to do it.

**Comment by jilljenn** [comment]
Thanks,

    export CFLAGS=-I/usr/local/opt/openssl/include
    opam install ssl

worked for me. (I googled "Cannot find libssl headers" and did *not* find this discussion, unfortunately.)

**Comment by mor1** [comment]
FWIW, if using the homebrew package `libressl`, I found the following worked:

```
CPPFLAGS=-I/usr/local/opt/libressl/include opam install ssl
```

**Comment by dsheets** [comment]
This was broken in opam for too long. I created and merged ocaml/opam-repository#5334 and ocaml/opam-repository#5335 to fix the situation. It's not clear to me that the include path addition is correct for older versions of OSX (say, with both homebrew OpenSSL and system OpenSSL of a different version installed) nor for all OpenSSL installations on OS X.

**Comment by dsheets** [comment]
I should also say, I'm sorry I missed out finding this issue or @ mentioning you, @smimram. I'd be very happy to have hot fixes contributed back into opam as soon as we find compatibility issues.

**Comment by smimram** [comment]
I would be more than happy to integrate a decent patch. The thing is that I don't really know how to test whether the OS is OS X and I have no easy access to and OS X machine to test. Moreover, I find this issue a bit strange, because I think that the path should be provided by ssl's .pc file. We are far from being the only one to use ssl, maybe someone would have time to check how other programs handle this in their configure.

@toots it would be nice if you could have a quick look at this...

**Comment by toots** [comment]
I've been having this issue and not only with ssl actually. I'm trying to figure out the issue. @smimram's remark on using `ssl.pc` is correct which is puzzling me.

**Comment by ruhatch** [comment]
To get this working with MacPorts installation of OpenSSL, I had to do:

    export CPPFLAGS=-I/opt/local/include
    opam install ssl

I tried `CFLAGS`, but I guess that gets overwritten by the hotfix!

**Comment by dsheets** [comment]
@ruhatch, I have fixed the (incorrect) `CFLAGS` override in ocaml/opam#5650 so `ssl.0.5.2` should now work out-of-the-box on OS X 10.11+ with MacPorts. I hope something like this gets included in the next release of the library.

**Comment by rleonid** [comment]
I've experienced a similar problem with the recent Sierra and brewed version. Modified the `opam` file to:
`"./configure --prefix %{prefix}% CPPFLAGS=\"$CPPFLAGS -I/usr/local/opt/openssl/include\" LDFLAGS=\"$LDFLAGS -L/usr/local/opt/openssl/lib\""`
