### ISSUE TITLE
OCaml-SSL fails to build with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by nbraud** [savonet/ocaml-ssl#26]
Debian is preparing for a transition to OpenSSL 1.1.0, and we discovered that OCaml-SSL fails to build with that version of OpenSSL.

You can find detail in [Debian bug #828462](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828462) and in the [build log](https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/ocaml-ssl_0.5.2-1_amd64-20160529-1458), but the gist of it seems to be that `CRYPTO_LOCK` is not declared anymore.

**Comment by smimram** [comment]
That's strange, I can build here with 1.1.0~pre5 (up to some minor modification I just commited, but not related to `CRYPTO_LOCK`)...

**Comment by toots** [comment]
Fixed in e49b6a7
