### ISSUE TITLE
deperecated bindings

### ISSUE THREAD

**Issue by colin-gd** [savonet/ocaml-ssl#31]
Hi, when trying to install ocsigenserver and eliom I stumpled upon a compilation error. According to Vasilis Papavasileiou (from the ocsigen mailing list) the error could be that the ocaml-ssl binding still refer to OpenSSL bindings deprecated in version 1.1. In fact, reverting the version of libssl to 1.0 fixed the issue.

The error reported when compiling ocsigenserver : 
```
/home/colin/.opam/4.04.0/lib/ssl/libssl_threads_stubs.a(ssl_stubs.o): In 
function 'get_method':
 /home/colin/.opam/4.04.0/build/ssl.0.5.3/src/ssl_stubs.c:277: 
undefined reference to 'SSLv23_client_method'
/home/colin/.opam/4.04.0/build/ssl.0.5.3/src/ssl_stubs.c:281: 
undefined reference to 'SSLv23_server_method'
/home/colin/.opam/4.04.0/build/ssl.0.5.3/src/ssl_stubs.c:285: 
undefined reference to 'SSLv23_method'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
 make[2]: *** [ocsigenserver.opt] Error 2
 make[1]: *** [all] Error 2
 make: *** [all] Error 2
```

**Comment by craff** [comment]
This is an old issue, openssl 1.1 is now compatible with ocaml-ssl (at least on my debian ;-). This issue can probably be closed as fixed ?
