### ISSUE TITLE
Build Failure on OS X High Sierra

### ISSUE THREAD

**Issue by MiloDavis** [savonet/ocaml-ssl#33]
This package is an upstream dependency for Tezos and in the newest version of OS X, Apple has started LibreSSL from OpenSSL. Though OS X users can install OpenSSL via Homebrew, there does not appear to be a way to link it in. This [issue](https://github.com/tezos/tezos/issues/123) details the problem and a few environment variables that can fix the issue.

**Comment by toots** [comment]
The `opam` package for `ssl` already has the required env variables:
```
build: [
  ["./configure" "--prefix" prefix] { os != "darwin" }
  ["sh" "-exc"
   "./configure --prefix %{prefix}% CPPFLAGS=\"$CPPFLAGS -I/opt/local/include -I/usr/local/opt/openssl/include\""
  ] { os = "darwin" }
  [make]
]
```
Were you trying to install manually or via `opam`?

**Comment by toots** [comment]
This should be fixed now.
