### ISSUE TITLE
ALPN extension support?

### ISSUE THREAD

**Issue by bobbypriambodo** [savonet/ocaml-ssl#37]
Hi there, I'm wondering if there is interest in ALPN support for `ssl`?

RFC: https://tools.ietf.org/html/rfc7301
Openssl doc: https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_alpn_select_cb.html

ALPN support is one of the requirements for supporting HTTP/2 in OCaml. I'm currently working on an implementation of it in `ocaml-tls`. I don't mind tackling this issue, but as I am new to writing C bindings in OCaml, I would love some pointers on how to start hacking.

Thanks!

**Comment by bobbypriambodo** [comment]
In particular, I'm thinking of adding the following functions to the `Ssl` module:

```ocaml
(** Set the list of supported ALPN protocols for negotiation to the context. *)
val set_context_alpn_protos : context -> string list -> unit

(** Set the callback to allow server to select the preferred protocol from client's available protocols. *)
val set_context_alpn_select_callback : context -> (string list -> string option) -> unit

(** Set the list of supported ALPN protocols for negotiation to the connection. *)
val set_alpn_protos : socket -> string list -> unit

(** Get the negotiated protocol from the connection. *)
val get_negotiated_alpn_protocol : socket -> string option
```

**Comment by smimram** [comment]
Pull requests are welcome :)
