### ISSUE TITLE
SSL: Method error with 0.5.6

### ISSUE THREAD

**Issue by mattjbray** [savonet/ocaml-ssl#40]
Could be related to the switch to `dune`?

Minimal repro:

```
FROM ocaml/opam2:alpine-3.7-ocaml-4.06

RUN opam repo set-url default https://opam.ocaml.org && opam update
RUN sudo apk add --no-cache m4 pkgconf libressl-dev
RUN opam install ssl=0.5.6 cohttp-lwt-unix lwt_ssl
```

```
$ docker build . -t ssl-repro
...
$ docker run -it --rm ssl-repro cohttp-curl-lwt https://reddit.com
cohttp-curl: internal error, uncaught exception:
             SSL: Method error
```

Also reproducible on my OSX machine.

**Comment by rgrinberg** [comment]
Thanks for the bug report. I can reproduce this as well. Debugging.

**Comment by rgrinberg** [comment]
Okay, I see what's the issue. The old code relied on a few defines being available that were discovered via autoconf. Will fix.

**Comment by rjbou** [comment]
I had the same error `SSL: Method error` while using `opam publish`. ftm, I'll freeze `ssl` to `0.5.5`.
