### ISSUE TITLE
OPAM Link for 0.5.6 release 404s

### ISSUE THREAD

**Issue by SimonJF** [savonet/ocaml-ssl#46]
Hi,

Thanks for your great work on this library!

The 0.5.6 link on https://opam.ocaml.org/packages/ssl/ssl.0.5.6/ is broken -- it points to https://github.com/savonet/ocaml-ssl/archive/v0.5.6.tar.gz instead of https://github.com/savonet/ocaml-ssl/archive/0.5.6.zip. I think 0.5.6 was re-released along with 0.5.7 6 days ago, according to the release page, which changed the archive name to be consistent with the other releases.

I'm happy to submit the PR to `opam-repository` to update the link, but some applications may depend on the previous stable `opam` link. In particular, I was using a snapshot of the OPAM repository as part of my POPL'19 artifact submission (https://popl19.sigplan.org/track/POPL-2019-Artifact-Evaluation). If possible, could you please re-release v.0.5.6 using the previous URL, so it's consistent with OPAM?

Thanks for your time!

**Comment by smimram** [comment]
Thanks for noticing this and letting me know. I changed the tag in order to match the previous convention and did not think about side effects. Both v0.5.6 and 0.5.6 should work now.

**Comment by SimonJF** [comment]
Thank you. Much appreciated!
