### ISSUE TITLE
Adding bindings for X509_digest

### ISSUE THREAD

**Issue by schubev** [savonet/ocaml-ssl#65]
I wish to use ocaml-ssl as part of a piece of server software in which clients connect using client certificates. The server should be able to remember said certificates and it would be quite handy to be able to do that by just saving certificate fingerprints. Unfortunately there currently aren’t any bindings for the `X509_digest` function which would give me said fingerprint.

Would a pull-request be welcome? I am willing and able to submit one.

As per my use case I would add something along these lines:

```ocaml
(* See EVP_sha1, EVP_sha256 and EVP_sha384 *)
type evp = [`SHA1 | `SHA256 | `SHA384]

(* The string would contain binary data, as opposed to hex or base64. *)
val digest : evp -> certificate -> string
```

**Comment by smimram** [comment]
Yes, such a PR would be very welcome!

**Comment by schubev** [comment]
I opened #66.
