### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by anmonteiro** [savonet/ocaml-ssl#67]
I'd like to release a library that depends on some new, unreleased functionality (e.g. #57, #58 and #60).

May I gently request a release of ocaml-ssl, at your earliest convenience? Thanks!

**Comment by smimram** [comment]
Done!

**Comment by anmonteiro** [comment]
Thanks a lot! Has it already hit OPAM? Would you like me to submit a PR there?

**Comment by smimram** [comment]
The PR is here: https://github.com/ocaml/opam-repository/pull/18071
