### ISSUE TITLE
TLS1_3_VERSION needs to be ifdef'ed

### ISSUE THREAD

**Issue by lindig** [savonet/ocaml-ssl#70]
Compilation of HEAD fails on openssl releases that don't define `TLS1_3_VERSION`. The code is in general careful by using `HAVE_TLS13` et al to avoid this but this is not the case in 

* https://github.com/savonet/ocaml-ssl/blob/master/src/ssl_stubs.c#L880-L914

A quick fix is in

* https://github.com/savonet/ocaml-ssl/pull/69

but a more systematic approach would be beneficial.

**Comment by dinosaure** [comment]
I can confirm a compilation error on `alpine-3.13` with OCaml 4.12.

**Comment by CraigFe** [comment]
This issue is still failing some of our CI running on `alpine-3.13`.

Is it possible to cherry-pick 5cbeba7025fedc09d4a3ce5c678ff7a19ca79a84 from https://github.com/savonet/ocaml-ssl/pull/63 and merge that as a separate change?

**Comment by psafont** [comment]
Fixed by https://github.com/savonet/ocaml-ssl/pull/73
